services:
  chatbotn:
    image: semantic-canvas:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8001:8000"
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/data_storage:/app/backend/data_storage
      - ./backend/chroma_db:/app/backend/chroma_db
      - sqlite_data:/app/backend/db
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - DATABASE_URL=sqlite:///./db/sql_app.db
      - NEXT_PUBLIC_API_URL=/api/v1
      - ARCADEDB_HOST=http://host.docker.internal:2480
      - OLLAMA_HOST=http://host.docker.internal:11434
    restart: unless-stopped

volumes:
  sqlite_data:
