# ==========================================
# Stage 1: Build Frontend
# ==========================================
FROM node:18-alpine AS frontend-builder
WORKDIR /app/frontend

# Install dependencies (use ci for reproducible builds if lockfile exists)
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci

# Copy source code
COPY frontend/ ./

# Build Next.js app (standalone mode configured in next.config.ts)
RUN npm run build

# ==========================================
# Stage 2: Final Runtime Image
# ==========================================
FROM python:3.11-slim

# Install system dependencies
# - nodejs/npm: For running the frontend server
# - supervisor: To manage both processes
# - build-essential: For python package compilation if needed
RUN apt-get update && apt-get install -y \
    nodejs \
    npm \
    supervisor \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# --- Backend Setup ---
WORKDIR /app/backend
COPY backend/requirements.txt .

# Install Python dependencies
# Use --no-cache-dir to keep image small
# Installing torch CPU version explicity if needed, otherwise rely on requirements
RUN pip install --no-cache-dir -r requirements.txt

# Copy Backend Code
COPY backend/ ./

# --- Frontend Setup ---
WORKDIR /app/frontend

# Copy standalone build from builder stage
COPY --from=frontend-builder /app/frontend/.next/standalone ./
COPY --from=frontend-builder /app/frontend/.next/static ./.next/static
COPY --from=frontend-builder /app/frontend/public ./public

# --- Final Configuration ---
WORKDIR /app

# Copy Seed Data (This will be populated by the prepare script externally)
# We assume the user runs `python scripts/prepare_docker_pack.py` before `docker build`
# usage: docker build -t semantic-canvas .
# The context should include the 'docker_pack' folder generated by the script.
# WAIT: The script creates 'docker_pack' at root. We need to COPY it.
# But Docker context rules... strictly speaking, if 'docker_pack' is in the root, we can copy it.
COPY docker_pack/ /app/seed_data/

# Verify seed data exists (will fail build if script wasn't run)
RUN ls -la /app/seed_data

# Copy Configs
COPY docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY docker/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Expose Ports
EXPOSE 3000 8000

# Environment Variables
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
ENV DATABASE_URL="sqlite:///./db/sql_app.db"

# Entrypoint
ENTRYPOINT ["/app/entrypoint.sh"]
