import os

path = r"c:\Users\opole\Downloads\ChatBotn\backend\app\services\rag_service.py"

with open(path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_lines = []
in_initialize = False
method_lines = []

for i, line in enumerate(lines):
    if "def initialize(self, model_name:" in line:
        in_initialize = True
        new_lines.append(line)
        continue
    
    if in_initialize and line.startswith("    def _get_postprocessors"):
        # We finished initialize, now process its lines
        
        # 1. Reconstruct the logical flow
        # This is a bit manual but necessary
        method_lines = [
            "        \"\"\"\n",
            "        Lazy Initialization of RAG Service.\n",
            "        Should be called automatically by public methods before use.\n",
            "        \"\"\"\n",
            "        # If already initialized and no specific model update requested, skip.\n",
            "        if self._initialized and not model_name:\n",
            "            return\n",
            "\n",
            "        with self._lock:\n",
            "            # Re-check inside lock\n",
            "            if self._initialized and not model_name:\n",
            "                return\n",
            "\n",
            "            debug_service.log(\"INFO\", \"Knowledge Base\", \"RAG\", \"Initializing RAG Service (loading library)...\")\n",
            "            self.init_error = None\n",
            "            \n",
            "            try:\n",
            "                from app.services.config_service import config_service\n",
            "                self.config_service = config_service\n",
            "                \n",
            "                # Heavy Imports - Localized to avoid import-time lag for the whole app\n",
            "                import chromadb\n",
            "                from llama_index.core import VectorStoreIndex, StorageContext, Settings\n",
            "                from llama_index.vector_stores.chroma import ChromaVectorStore\n",
            "                from llama_index.core.node_parser import SentenceSplitter\n",
            "                \n",
            "                # Soft dependencies for metadata extraction\n",
            "                try:\n",
            "                    from llama_index.llms.ollama import Ollama\n",
            "                except ImportError:\n",
            "                    print(\"[RAGService] Warning: `llama-index-llms-ollama` not found. Metadata extraction with Ollama will be disabled.\")\n",
            "\n",
            "                try:\n",
            "                    from llama_index.llms.openai import OpenAI\n",
            "                except ImportError:\n",
            "                    print(\"[RAGService] Warning: `llama-index-llms-openai` not found. Metadata extraction with OpenAI will be disabled.\")\n",
            "\n",
            "                # Load RAG Config\n",
            "                config = self.config_service.get_config()\n",
            "                rag_config = config.get(\"rag_config\", {})\n",
            "                self.querying_config = config.get(\"querying_config\", {\n",
            "                    \"similarity_top_k\": 5,\n",
            "                    \"similarity_cutoff\": None,\n",
            "                    \"retrieval_mode\": \"embedding\",\n",
            "                    \"postprocessor\": \"none\",\n",
            "                    \"postprocessor_config\": {},\n",
            "                    \"response_mode\": \"simple\"\n",
            "                })\n",
            "                \n",
            "                # --- Resolve Embedding Model from Preset (Priority) ---\n",
            "                embedding_preset = self.config_service.get_default_embedding_preset()\n",
            "                \n",
            "                # Logic: Use provided model_name if available, else use default.\n",
            "                if model_name:\n",
            "                    custom_preset = self.config_service.get_preset_config(model_name)\n",
            "                    llm_preset = custom_preset if custom_preset else self.config_service.get_default_llm_preset()\n",
            "                else:\n",
            "                    llm_preset = self.config_service.get_default_llm_preset()\n",
            "                \n",
            "                # Sync LlamaIndex Global Settings with User Config\n",
            "                if llm_preset:\n",
            "                    raw_window = llm_preset.get(\"context_window\", 4096)\n",
            "                    # Apply safety buffer of 4000 tokens to account for tokenizer discrepancies\n",
            "                    window = max(2048, raw_window - 4000)\n",
            "                    print(f\"[RAGService] Syncing Settings.context_window to {window} (raw: {raw_window}) from preset '{llm_preset['name']}'\")\n",
            "                    Settings.context_window = window\n",
            "                    \n",
            "                    # Sync Global LLM for synthesis\n",
            "                    from app.services.llm_service import llm_service\n",
            "                    \n",
            "                    active_model = llm_preset[\"name\"]\n",
            "                    \n",
            "                    # Check if Settings.llm is already set to this model to avoid redundant init\n",
            "                    current_llm = getattr(Settings, \"llm\", None)\n",
            "                    if current_llm and hasattr(current_llm, \"model_name\") and current_llm.model_name == active_model:\n",
            "                        print(f\"[RAGService] Settings.llm already set to '{active_model}'. Skipping re-sync.\")\n",
            "                    else:\n",
            "                        Settings.llm = llm_service._get_llama_index_model(active_model)\n",
            "                        print(f\"[RAGService] Syncing Settings.llm to model '{active_model}'\")\n",
            "                else:\n",
            "                    print(f\"[RAGService] No LLM Preset found. Using default context_window/llm.\")\n",
            "\n",
            "                if embedding_preset:\n",
            "                    # Use Preset\n",
            "                    model = embedding_preset.get(\"model_name\")\n",
            "                    preset_type = embedding_preset.get(\"type\")\n",
            "                    \n",
            "                    if preset_type == \"remote\":\n",
            "                        provider = \"openai\"\n",
            "                        # Map Preset fields to RAG usage\n",
            "                        api_key = embedding_preset.get(\"model_api_key\") or embedding_preset.get(\"service_api_key\")\n",
            "                        api_base = embedding_preset.get(\"api_url\")\n",
            "                    else:\n",
            "                        provider = \"ollama\"\n",
            "                        api_key = None\n",
            "                        api_base = None\n",
            "                        \n",
            "                    print(f\"[RAGService] Using Default Embedding Preset: {embedding_preset.get('name')} ({provider}/{model})\")\n",
            "                else:\n",
            "                    # Try legacy rag_config but NO hardcoded defaults\n",
            "                    provider = rag_config.get(\"embedding_provider\")\n",
            "                    model = rag_config.get(\"embedding_model\")\n",
            "                    api_key = rag_config.get(\"embedding_api_key\")\n",
            "                    api_base = None\n",
            "                    \n",
            "                    if not model:\n",
            "                        msg = \"CRITICAL: No default embedding model configured in presets or rag_config. Initialization aborted.\"\n",
            "                        print(f\"[RAGService] {msg}\")\n",
            "                        self.init_error = msg\n",
            "                        self.index = None\n",
            "                        return\n",
            "                    \n",
            "                    print(f\"[RAGService] No Default Embedding Preset. Using configured legacy: {provider}/{model}\")\n",
            "\n",
            "                parsing_strategy = rag_config.get(\"parsing_strategy\", \"recursive\")\n",
            "                chunk_size = int(rag_config.get(\"chunk_size\", 512))\n",
            "                chunk_overlap = int(rag_config.get(\"chunk_overlap\", 50))\n",
            "                self.enable_metadata = rag_config.get(\"enable_metadata\", False)\n",
            "                \n",
            "                print(f\"[RAGService] Initializing with Provider={provider}, Model={model}, Strategy={parsing_strategy}\")\n",
            "\n",
            "                # 1. Configure Embedding Model\n",
            "                if provider == \"openai\":\n",
            "                    try:\n",
            "                        from llama_index.embeddings.openai import OpenAIEmbedding\n",
            "                        if not api_key:\n",
            "                            print(\"[RAGService] Warning: OpenAI provider selected but no API Key found.\")\n",
            "                        \n",
            "                        embed_args = {\n",
            "                            \"model_name\": model,\n",
            "                        }\n",
            "                        if api_key:\n",
            "                            embed_args[\"api_key\"] = api_key\n",
            "                        if api_base:\n",
            "                            embed_args[\"api_base\"] = api_base\n",
            "                            \n",
            "                        Settings.embed_model = OpenAIEmbedding(**embed_args)\n",
            "                        print(f\"[RAGService] Configured OpenAI Embedding: {model}\")\n",
            "                    except ImportError:\n",
            "                        msg = \"OpenAI provider selected but `llama-index-embeddings-openai` not installed.\"\n",
            "                        print(f\"[RAGService] Error: {msg}\")\n",
            "                        self.init_error = msg\n",
            "                        self.index = None\n",
            "                        return\n",
            "                    except Exception as e:\n",
            "                        msg = f\"Error configuring OpenAI Embedding: {str(e)}\"\n",
            "                        print(f\"[RAGService] {msg}\")\n",
            "                        self.init_error = msg\n",
            "                        self.index = None\n",
            "                        return\n",
            "                else:\n",
            "                    self._configure_ollama(model)\n",
            "\n",
            "                # 2. Configure Text Splitter / Node Parser\n",
            "                if parsing_strategy == \"window\":\n",
            "                    from llama_index.core.node_parser import SentenceWindowNodeParser\n",
            "                    Settings.node_parser = SentenceWindowNodeParser.from_defaults(\n",
            "                        window_size=3,\n",
            "                        window_metadata_key=\"window\",\n",
            "                        original_text_metadata_key=\"original_text\",\n",
            "                    )\n",
            "                    print(\"[RAGService] Configured SentenceWindowNodeParser\")\n",
            "                elif parsing_strategy == \"token\":\n",
            "                    from llama_index.core.node_parser import TokenTextSplitter\n",
            "                    Settings.text_splitter = TokenTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)\n",
            "                    Settings.node_parser = Settings.text_splitter\n",
            "                    print(f\"[RAGService] Configured TokenTextSplitter (size={chunk_size}, overlap={chunk_overlap})\")\n",
            "                elif parsing_strategy == \"markdown\":\n",
            "                    from llama_index.core.node_parser import MarkdownNodeParser\n",
            "                    Settings.node_parser = MarkdownNodeParser()\n",
            "                    print(\"[RAGService] Configured MarkdownNodeParser\")\n",
            "                elif parsing_strategy == \"hierarchical\":\n",
            "                    from llama_index.core.node_parser import HierarchicalNodeParser\n",
            "                    Settings.node_parser = HierarchicalNodeParser.from_defaults(\n",
            "                        chunk_sizes=[chunk_size*4, chunk_size*2, chunk_size]\n",
            "                    )\n",
            "                    print(f\"[RAGService] Configured HierarchicalNodeParser (sizes={[chunk_size*4, chunk_size*2, chunk_size]})\")\n",
            "                elif parsing_strategy == \"semantic\":\n",
            "                    from llama_index.core.node_parser import SemanticSplitterNodeParser\n",
            "                    if Settings.embed_model:\n",
            "                        Settings.node_parser = SemanticSplitterNodeParser(\n",
            "                            buffer_size=1, \n",
            "                            breakpoint_percentile_threshold=95, \n",
            "                            embed_model=Settings.embed_model\n",
            "                        )\n",
            "                        print(\"[RAGService] Configured SemanticSplitterNodeParser\")\n",
            "                    else:\n",
            "                        print(\"[RAGService] Error: Semantic Splitter requires an embedding model. Falling back to SentenceSplitter.\")\n",
            "                        Settings.text_splitter = SentenceSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)\n",
            "                        Settings.node_parser = Settings.text_splitter\n",
            "                else:\n",
            "                    Settings.text_splitter = SentenceSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)\n",
            "                    Settings.node_parser = Settings.text_splitter\n",
            "                    print(f\"[RAGService] Configured SentenceSplitter (size={chunk_size}, overlap={chunk_overlap})\")\n",
            "\n",
            "                # Initialize Chroma Client\n",
            "                try:\n",
            "                    if self.chroma_client is None:\n",
            "                        print(f\"DEBUG: Initializing ChromaDB PersistentClient at {self.persist_directory}\")\n",
            "                        self.chroma_client = chromadb.PersistentClient(path=self.persist_directory)\n",
            "                        print(\"DEBUG: ChromaDB Client successfully initialized.\")\n",
            "                    else:\n",
            "                        print(\"DEBUG: ChromaDB Client already initialized. Reusing.\")\n",
            "                except Exception as e:\n",
            "                    err_msg = str(e)\n",
            "                    debug_service.log(\"ERROR\", \"Knowledge Base\", \"RAG\", f\"CRITICAL ERROR: Failed to initialize ChromaDB: {err_msg}\")\n",
            "                    if \"tenant\" in err_msg.lower() or \"sqlite\" in err_msg.lower() or \"database\" in err_msg.lower():\n",
            "                        print(\"[RAGService] Detected potential DB corruption. Attempting to recover...\")\n",
            "                        try:\n",
            "                            import shutil\n",
            "                            import time\n",
            "                            timestamp = int(time.time())\n",
            "                            backup_path = f\"{self.persist_directory}_corrupt_{timestamp}\"\n",
            "                            if os.path.exists(self.persist_directory):\n",
            "                                print(f\"[RAGService] Renaming corrupt DB to {backup_path}\")\n",
            "                                try:\n",
            "                                    os.rename(self.persist_directory, backup_path)\n",
            "                                except OSError as rename_err:\n",
            "                                    print(f\"[RAGService] Rename failed: {rename_err}. (likely locked by another process).\")\n",
            "                                    time.sleep(1)\n",
            "                                    try: os.rename(self.persist_directory, backup_path)\n",
            "                                    except: pass\n",
            "                            print(\"[RAGService] Retrying initialization with fresh DB...\")\n",
            "                            self.chroma_client = chromadb.PersistentClient(path=self.persist_directory)\n",
            "                            self.chroma_collection = self.chroma_client.get_or_create_collection(\"chatbot_rag_v2\")\n",
            "                            print(\"[RAGService] Recovery successful. Fresh DB initialized.\")\n",
            "                            self.vector_store = ChromaVectorStore(chroma_collection=self.chroma_collection)\n",
            "                            self.storage_context = StorageContext.from_defaults(vector_store=self.vector_store)\n",
            "                            self.index = VectorStoreIndex.from_documents([], storage_context=self.storage_context)\n",
            "                            self._initialized = True\n",
            "                            return\n",
            "                        except Exception as recovery_err:\n",
            "                            print(f\"CRITICAL: Auto-recovery failed: {recovery_err}\")\n",
            "                            self.init_error = f\"ChromaDB Recovery Failed: {recovery_err}\"\n",
            "                    import traceback\n",
            "                    traceback.print_exc()\n",
            "                    self.chroma_client = None\n",
            "                    self.init_error = f\"ChromaDB Initialization Exception: {str(e)}\"\n",
            "                    self.index = None\n",
            "                    return\n",
            "\n",
            "                self.chroma_collection = self.chroma_client.get_or_create_collection(\"chatbot_rag_v2\")\n",
            "                try: print(f\"[RAGService] Collection '{self.chroma_collection.name}' initialized.\")\n",
            "                except: pass\n",
            "                \n",
            "                self.vector_store = ChromaVectorStore(chroma_collection=self.chroma_collection)\n",
            "                self.storage_context = StorageContext.from_defaults(vector_store=self.vector_store)\n",
            "                try:\n",
            "                    self.index = VectorStoreIndex.from_vector_store(self.vector_store, storage_context=self.storage_context)\n",
            "                except Exception:\n",
            "                    self.index = VectorStoreIndex.from_documents([], storage_context=self.storage_context)\n",
            "                \n",
            "                self._initialized = True\n",
            "            except Exception as e:\n",
            "                self.init_error = f\"Initialization Exception: {str(e)}\"\n",
            "                print(f\"RAGService initialization failed: {e}\")\n",
            "                import traceback\n",
            "                traceback.print_exc()\n",
            "                self.chroma_client = None\n",
            "                self.chroma_collection = None\n",
            "                self.vector_store = None\n",
            "                self.storage_context = None\n",
            "                self.index = None\n"
        ]
        new_lines.extend(method_lines)
        in_initialize = False
        continue

    if not in_initialize:
        new_lines.append(line)

with open(path, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)
print("File reconstructed successfully.")
