from pydantic import BaseModel, Field
from typing import List, Optional

class GapMigrationStep(BaseModel):
    """Represents a single actionable step to migrate from Baseline to Target."""
    order: int = Field(..., description="The sequence number of the migration step (e.g., 1, 2, 3).")
    title: str = Field(..., description="A short, descriptive title for the step.")
    description: str = Field(..., description="Detailed explanation of what needs to be done.")
    layer_impact: str = Field(..., description="The primary architecture layer impacted (e.g., 'Business Layer', 'Application Layer').")

class GapDiffElement(BaseModel):
    """Represents a single architectural element and its evolution state."""
    element_id: str = Field(..., description="Unique identifier of the element if available.")
    name: str = Field(..., description="Name of the component or element.")
    type: str = Field(..., description="The Archimate element type (e.g., 'BusinessActor', 'ApplicationComponent').")
    status: str = Field(..., description="The gap status: 'added', 'removed', 'modified', or 'unchanged'.")
    details: Optional[str] = Field(None, description="Explanation of the modification or reason for addition/removal.")

class GapAnalysisReport(BaseModel):
    """The complete output generated by the Gap Analysis Tool."""
    added_count: int = Field(0, description="Total number of elements added in the target state.")
    removed_count: int = Field(0, description="Total number of elements removed from the baseline state.")
    modified_count: int = Field(0, description="Total number of elements modified between states.")
    migration_steps: List[GapMigrationStep] = Field(default_factory=list, description="Logical sequence of migration steps.")
    diff_elements: List[GapDiffElement] = Field(default_factory=list, description="List of all elements highlighting their diff status.")
    
    # We can expand this later to include raw Archimate JSON for rendering
    archimate_diff_json: Optional[dict] = Field(None, description="Optional: Raw Archimate JSON data with color/diff metadata attached for visual rendering.")
